// https://svgwg.org/svg2-draft/types.html#InterfaceSVGAnimatedBoolean
[Exposed=Window]
interface SVGAnimatedBoolean {
    attribute boolean baseVal;
    [ImplementedAs=base_val] readonly attribute boolean animVal;
};
